//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSW.B2B.Database.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSW.B2B.Database.Resources.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=&apos;&quot; + dbFileNameAndPath + &quot;&apos;;Persist Security Info=False;Max Database Size=4091;
        ///
        ///Create Database EstimateHistory;
        ///GO
        ///
        ///use [EstimateHistory]
        ///Go
        ///
        ///CREATE TABLE [BLCK] ([ID] int NOT NULL Primary Key  
        ///, [DESC] nvarchar(50) NOT NULL
        ///, [REM] nvarchar(255)  
        ///);
        ///GO
        ///
        ///CREATE TABLE [GRUP] ([ID] int NOT NULL Primary Key  
        ///, [DESC] nvarchar(50) NOT NULL
        ///, [GRP_ID] nvarchar(255) NOT NULL
        ///, [NATURE] int  
        ///, [SUBLED] int NOT NULL
        ///, [REM] nvarchar(256) 
        ///);
        ///GO
        ///
        ///CREATE TABLE [UNIT] ([ID] int [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbCreationScript {
            get {
                return ResourceManager.GetString("dbCreationScript", resourceCulture);
            }
        }
    }
}
